"""empty message

Revision ID: ed8db8c8da7a
Revises: 155d33fa0356
Create Date: 2024-11-04 19:46:36.919313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8db8c8da7a'
down_revision = '155d33fa0356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('img_ilustrativa',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('img_ilustrativa',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
